In [1]:
import numpy as np
import pandas as pd

In [2]:
input_pre = '../csv_files/input_files/'
output_pre = '../csv_files/output_files/' 
main = pd.read_csv(output_pre + 'promote_database.csv')
print(main.shape)

(2400, 466)

C:\Users\ridhi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (33,119,121,182,184,223,226,230,231,233,236,237,241,245,263,264,278,298,299,302,394,436,438,439,441,452,453,455,456) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
long = pd.read_csv(input_pre + 'longitudinal.csv')
main = pd.read_csv(input_pre + 'main.csv')

C:\Users\ridhi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (4,8,14,23,26,27,31,33,34,38,42,77,100,119,142,171,172,197,199,201,205,211,215,217,219,221,241,243,246,249,252,255,258,264,273,276,279,282,346,357,359,371,462,463,467,470,471,472,595,597,600,606,612,621,627,630,633,636,643,647,651,655,699,713,715,784,786,798,878,879,884,923,935,939,1095,1099,1101,1103) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\ridhi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (10,31,56,73,84,85,98,106,115,117,119,152,153,166,169,174,178,180,182,195,224,233,234,235,239,261,262,276,296,297,300,390,391,392,395,397,399,401,403,405,407,409,411,413,418,419,421,422,424,425,427,428,430,431,433,434,436,437,439,453,454,460,461) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
long.shape

(1545, 2305)

In [5]:
p_start = long.columns.get_loc("primary_questionnaire_timestamp")
print(p_start)
p_end = long.columns.get_loc("primary_questionnaire_complete") +1
print(p_end)
s_start = long.columns.get_loc("promote_self_reported_outcomes_timestamp")
print(s_start)
s_end = long.columns.get_loc("promote_self_reported_outcomes_complete")+1
print(s_end)

18
171
171
462

In [7]:
id_series = list(long['id_participant_l'])
#list(id_series)

In [8]:
primary_df = long.iloc[:,p_start:p_end]
#primary_df.shape
primary_df['id_participant'] = id_series
primary_df.shape

(1545, 154)

In [9]:
self_df = long.iloc[:,s_start:s_end]
#primary_df.head()
self_df['id_participant'] = id_series

In [10]:
self_df.shape
#self_df['id_participant']

(1545, 292)

###  Self Reported Questions

In [11]:
len(self_df[self_df['promote_self_reported_outcomes_complete']==2])

94

In [12]:
#self_df[self_df['dmt_now']==2]
dmt_ref = {
    "dmtlist_now___1":"aubagio",
    "dmtlist_now___2":"avonex",
    "dmtlist_now___3":"betaseron",
    "dmtlist_now___4":"copaxone",
    "dmtlist_now___5":"extavia",
    "dmtlist_now___6":"gilenya",
    "dmtlist_now___7":"novantrone",
    "dmtlist_now___8":"plegridy",
    "dmtlist_now___9":"rebif",
    "dmtlist_now___10":"tecfidera",
    "dmtlist_now___11":"tysabri",
    "dmtlist_now___12":"other",
    "dmtlist_now___13":"rituxan",
    "dmtlist_now___14":"zinbryta",
    "dmtlist_now___15":"ocrevus",
    "dmtlist_now___16":"lemtrada",
}

In [13]:
import math
long.loc[long['dmt_now_tecfidera_duration'].isnull() == False, 'id_participant_l']

292     PRT170209
964     PRT180699
1203    PRT190894
1209    PRT190900
1329    PRT191020
1334    PRT191025
1347    PRT191038
Name: id_participant_l, dtype: object

In [14]:
for i, row in self_df.iterrows():
    a = row.dmt_now
    if a == 1 or a == 2:
        index = 1
        for i in range(12):
            col_name = 'dmtlist_now___' + str(i+1)
            if row[col_name] == 1:
                cols = []
                cols.append(col_name)
                for a in cols:
                    if a == "dmtlist_now___12":
                        print(row.dmt_now_other)
                    col_name2 = 'dmt_now_'+ dmt_ref[a] +'_duration'
                    if row[col_name2] == math.nan:
                        print(row.id_participant)
                    col_name3 = 'dmt_now_'+ dmt_ref[a] +'_start'
                    if row[col_name3] == math.nan:
                        print(row.id_participant)

In [15]:
dmtlist_ref = {
    "dmtlist_past___1":"aubagio",
    "dmtlist_past___2":"avonex",
    "dmtlist_past___3":"betaseron",
    "dmtlist_past___4":"copaxone",
    "dmtlist_past___5":"extavia",
    "dmtlist_past___6":"gilenya",
    "dmtlist_past___7":"novantrone",
    "dmtlist_past___8":"plegridy",
    "dmtlist_past___9":"rebif",
    "dmtlist_past___10":"tecfidera",
    "dmtlist_past___11":"tysabri",
    "dmtlist_past___12":"other",
    "dmtlist_past___13":"rituxan",
    "dmtlist_past___14":"zinbryta",
    "dmtlist_past___15":"ocrevus",
    "dmtlist_past___16":"lemtrada",
}

In [16]:
import math
for i, row in self_df.iterrows():
    a = row.dmt_past
    if a == 1 or a == 2:
        index = 1
        for i in range(12):
            col_name = 'dmtlist_past___' + str(i+1)
            if row[col_name] == 1:
                cols = []
                cols.append(col_name)
                for a in cols:
                    if a == "dmtlist_past___12":
                        print(row.dmt_past_other)
                        break
                    col_name2 = 'dmt_past_'+ dmtlist_ref[a] +'_duration'
                    if row[col_name2] == math.nan:
                        print(row.id_participant)
                    col_name3 = 'dmt_past_'+ dmtlist_ref[a] +'_start'
                    if col_name3 == 'dmt_past_copaxone_start': 
                        col_name3 = 'dmt_past_copaxon_start' 
                    if row[col_name3] == math.nan:
                        print(row.id_participant)
                    col_name4 = 'dmt_past_'+ dmtlist_ref[a] +'_stop'
                    if row[col_name3] == math.nan:
                        print(row.id_participant)

IVGA, PLAMSAMA PHESIS, CHEMO
Ampyra
nan

In [17]:
ex_start = self_df.columns.get_loc("dmt_now")
print(ex_start)
ex_end = self_df.columns.get_loc("dmt_past_zinbryta_stop") +1
print(ex_end)

5
116

In [18]:
df = self_df.drop(self_df.iloc[:, 5:116], axis = 1)

In [19]:
df.describe()

,sex_sro,ms_category,ms_neurocare,fams4_mobility_gp3_familyneed,fams4_mobility_gf1_work,fams4_mobility_an6_walking,fams4_mobility_itu3_social,fams4_mobility_cn55_legs,fams4_mobility_ms1_public,fams4_mobility_ms2_plan,...,ltsu___3,ltsu___4,ltsu___5,ltsu___6,ltsu___7,ltsu___8,ltsu___9,ltsu___0,ltsu___99,promote_self_reported_outcomes_complete
count,113.000000,70.000000,78.000000,111.000000,111.000000,111.000000,111.000000,111.000000,110.000000,111.000000,...,1138.000000,1138.000000,1138.000000,1138.000000,1138.000000,1138.0,1138.000000,1138.000000,1138.000000,1138.000000
mean,1.336283,4.000000,0.871795,0.747748,2.783784,0.918919,0.936937,2.693694,0.727273,1.207207,...,0.007030,0.002636,0.001757,0.007030,0.008787,0.0,0.007909,0.047452,0.005272,0.167838
std,0.474541,1.251086,0.336482,1.082661,1.497910,1.280164,1.169921,1.333436,1.091326,1.459247,...,0.083586,0.051299,0.041904,0.083586,0.093369,0.0,0.088617,0.212696,0.072452,0.552394
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,1.000000,3.000000,1.000000,0.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,1.000000,4.000000,1.000000,0.000000,4.000000,0.000000,0.000000,3.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
75%,2.000000,4.000000,1.000000,1.000000,4.000000,2.000000,2.000000,4.000000,1.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
max,2.000000,7.000000,1.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,2.000000

In [20]:
complete_df = df[df['promote_self_reported_outcomes_complete']==2]
len(complete_df)

94

In [24]:
nans = lambda complete_df: complete_df[complete_df.isnull().any(axis=1)]

In [25]:
nan_record = nans(complete_df)

In [26]:
nan_record.to_csv("promote_self_reported_outcomes_complete.csv")

### Primary questionarrie

In [23]:
#list(primary_df)

In [24]:
complete_records_primary = primary_df[primary_df['primary_questionnaire_complete']==2]
len(complete_records_primary)

94

In [25]:
nans = lambda complete_records_primary: complete_records_primary[complete_records_primary.isnull().any(axis=1)]

In [26]:
pdf = nans(complete_records_primary)

In [27]:
pdf.to_csv("primary_questionnaire_complete.csv")

In [28]:
u_start = long.columns.get_loc("dob_8e881e")
print(u_start)
u_end = long.columns.get_loc("update_questionnaire_complete")+1
print(u_end)

461
876

In [29]:
update_df = long.iloc[:,u_start:u_end]
update_df['id_participant'] = id_series
update_df.shape

(1129, 416)

### Food Frequency

In [30]:
f_start = long.columns.get_loc("dob_ffq")
print(f_start)
f_end = long.columns.get_loc("food_frequency_complete")+1
print(f_end)

877
1104

In [31]:
food_df = long.iloc[:,f_start:f_end]
food_df['id_participant'] = id_series
food_df.shape

(1129, 228)

In [32]:
#list(food_df)

In [33]:
complete_records_food = food_df[food_df['food_frequency_complete']==2]
nans = lambda complete_records_food: complete_records_food[complete_records_food.isnull().any(axis=1)]
fdf = nans(complete_records_food)
fdf.to_csv("food_frequency_complete.csv")
len(complete_records_food)

210

In [34]:
#list(long)

In [35]:
col_name = ['id_participant_l','id_med_record_number','dob','age_pq','sex_pq','subject_group','primary_questionnaire_complete',
            'promote_self_reported_outcomes_complete','update_questionnaire_complete','food_frequency_complete']

#### Starting for combine results

In [36]:
import math
for i, row in long.iterrows():
    a = row.dmt_past
    if a == 1 or a == 2:
        index = 1
        for i in range(12):
            col_name = 'dmtlist_past___' + str(i+1)
            if row[col_name] == 1:
                cols = []
                cols.append(col_name)
                for a in cols:
                    if a == "dmtlist_past___12":
                        print(row.dmt_past_other)
                        break
                    col_name2 = 'dmt_past_'+ dmtlist_ref[a] +'_duration'
                    if row[col_name2] == math.nan:
                        print(row.id_participant)
                    col_name3 = 'dmt_past_'+ dmtlist_ref[a] +'_start'
                    if col_name3 == 'dmt_past_copaxone_start': 
                        col_name3 = 'dmt_past_copaxon_start' 
                    if row[col_name3] == math.nan:
                        print(row.id_participant)
                    col_name4 = 'dmt_past_'+ dmtlist_ref[a] +'_stop'
                    if row[col_name3] == math.nan:
                        print(row.id_participant)

IVGA, PLAMSAMA PHESIS, CHEMO
Ampyra

In [37]:
for i, row in self_df.iterrows():
    a = row.dmt_now
    if a == 1 or a == 2:
        index = 1
        for i in range(12):
            col_name = 'dmtlist_now___' + str(i+1)
            if row[col_name] == 1:
                cols = []
                cols.append(col_name)
                for a in cols:
                    if a == "dmtlist_now___12":
                        print(row.dmt_now_other)
                    col_name2 = 'dmt_now_'+ dmt_ref[a] +'_duration'
                    if row[col_name2] == math.nan:
                        print(row.id_participant)
                    col_name3 = 'dmt_now_'+ dmt_ref[a] +'_start'
                    if row[col_name3] == math.nan:
                        print(row.id_participant)

In [38]:
ex_start = long.columns.get_loc("dmt_now")
print(ex_start)
ex_end = long.columns.get_loc("dmt_past_zinbryta_stop") +1
print(ex_end)

174
285

In [39]:
df_full = long.drop(long.iloc[:, 174:285], axis = 1)

In [40]:
complete_df = df_full[(df_full['promote_self_reported_outcomes_complete']==2) | (df_full['primary_questionnaire_complete']==2) 
                        |(df_full['food_frequency_complete']==2) | (df_full['update_questionnaire_complete']==2)]

In [41]:
complete_df

,id_participant_l,redcap_event_name,redcap_survey_identifier,name_first,name_middle,name_last,dob,doe,id_primary,id_secondary,...,promis_pfc53_qposition,promis_pfc54,promis_pfc54_tscore,promis_pfc54_stderror,promis_pfc54_qposition,promis_pfc56,promis_pfc56_tscore,promis_pfc56_stderror,promis_pfc56_qposition,promis_bank_v12_physical_function_complete
4,PRT170003,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,PRT170009,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PRT170010,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,PRT170013,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PRT170015,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,PRT170016,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,PRT170020,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,PRT170021,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,PRT170022,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,PRT170023,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,PRT170024,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,PRT170027,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,PRT170029,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,PRT170030,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,PRT170031,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,PRT170032,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,PRT170034,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,PRT170035,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,PRT170036,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,PRT170037,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,PRT170041,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,PRT170042,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,PRT170043,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,PRT170046,year_02_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,PRT170047,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,PRT170049,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,PRT170053,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,PRT170055,year_03_arm_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,PRT170056,year_01_arm_1,NaN,Emily,NaN,Brown,NaN,2017-02-02,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,PRT170057,year_01_arm_1,NaN,Jeff,NaN,Allshouse,NaN,2017-02-02,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,PRT190944,year_01_arm_4,NaN,Terri,NaN,Grinner,NaN,2019-03-13,PRT190944,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1055,PRT190945,year_01_arm_4,NaN,Sherri,NaN,Thornton,NaN,2019-03-13,PRT190945,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1056,PRT190946,year_01_arm_4,NaN,Phil,NaN,Ahwesh,NaN,2019-03-13,PRT190946,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1057,PRT190947,year_01_arm_4,NaN,Adrianna,NaN,Danna,NaN,2019-03-13,PRT190947,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1058,PRT190948,year_01_arm_4,NaN,Nancy,NaN,Ley,NaN,2019-03-13,PRT190948,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,PRT190949,year_01_arm_4,NaN,Vicki,NaN,Carson,NaN,2019-03-13,PRT190949,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,PRT190950,year_01_arm_4,NaN,Isaac,NaN,Callihan,NaN,2019-03-13,PRT190950,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,PRT190952,year_01_arm_4,NaN,Judith,NaN,Hallinen,NaN,2019-04-05,PRT190952,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063,PRT190953,year_01_arm_4,NaN,Christopher,NaN,Revello,NaN,2019-04-08,PRT90953,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064,PRT190954,year_01_arm_4,NaN,Carrie,NaN,Lipscomb,NaN,2019-04-08,PRT190954,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1065,PRT190955,year_01_arm_4,NaN,Karen,D,Shaver,1969-07-14,2019-04-10,PRT190955,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1066,PRT190956,year_01_arm_4,NaN,Jazmin,NaN,Navarro,NaN,2019-04-10,PRT190956,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1067,PRT190957,year_01_arm_4,NaN,Dennis,NaN,Moore,1950-09-18,2019-04-11,PRT90957,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1070,PRT190960,year_01_arm_4,NaN,Maria,Guadalupe Madrigal,Garcia,NaN,2019-04-12,PRT190960,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076,PRT190966,year_01_arm_4,NaN,John,R,Deklewa,1974-08-03,2019-04-17,PRT190966,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1077,PRT190967,year_01_arm_4,NaN,Ruby,M,Mangham,1944-11-26,2019-04-18,PRT90967,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1079,PRT190969,year_01_arm_4,NaN,Bruce,NaN,Migota,1969-07-03,2019-04-19,PRT190969,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1080,PRT190970,year_01_arm_4,NaN,Christie,NaN,Yimin,1984-07-01,2019-04-23,PRT19970,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1081,PRT190971,year_01_arm_4,NaN,Tia,S,Chutz,1984-09-08,2019-04-23,PRT190971,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1092,PRT190982,year_01_arm_4,NaN,Justin,NaN,Foreman,NaN,2019-04-29,PRT190982,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1093,PRT190983,year_01_arm_4,NaN,Paul,A,Hensel,1979-02-18,2019-04-29,PRT190983,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1094,PRT190984,year_01_arm_4,NaN,Holly,H,Sarver,1964-03-26,2019-04-29,PRT190984,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1100,PRT190990,year_01_arm_4,NaN,Daniel,L,Taylor,NaN,2019-05-06,PRT190990,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103,PRT190993,year_01_arm_4,NaN,Becki,L,Fanala,1972-06-09,2019-05-09,PRT190993,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1104,PRT190994,year_01_arm_4,NaN,William,R,McNees,1955-01-06,2019-05-09,PRT190994,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1105,PRT190995,year_01_arm_4,NaN,Louella,NaN,Kuhn,1960-10-13,2019-05-10,PRT190995,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106,PRT190996,year_01_arm_4,NaN,Eric,NaN,Menhart,1979-04-16,2019-05-10,PRT190996,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1107,PRT190997,year_01_arm_4,NaN,Teresa,NaN,DeVoe,1977-04-16,2019-05-10,PRT190997,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,PRT191003,year_01_arm_4,NaN,Emma,NaN,Clites,1973-11-22,2019-05-14,PRT191003,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,PRT191006,year_01_arm_4,NaN,Christine,NaN,Scalamogna,1943-01-14,2019-05-15,PRT191006,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
a1 = complete_df[['id_participant_l','id_med_record_number','dob','doe','subject_group','primary_questionnaire_complete',
            'promote_self_reported_outcomes_complete','update_questionnaire_complete','food_frequency_complete']]

In [43]:
a1

,id_participant_l,id_med_record_number,dob,doe,subject_group,primary_questionnaire_complete,promote_self_reported_outcomes_complete,update_questionnaire_complete,food_frequency_complete
4,PRT170003,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
10,PRT170009,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
12,PRT170010,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
16,PRT170013,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
19,PRT170015,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
21,PRT170016,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
25,PRT170020,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
27,PRT170021,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
29,PRT170022,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
31,PRT170023,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
33,PRT170024,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
36,PRT170027,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
39,PRT170029,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
41,PRT170030,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
43,PRT170031,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
45,PRT170032,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
48,PRT170034,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
50,PRT170035,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
52,PRT170036,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
54,PRT170037,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
59,PRT170041,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
61,PRT170042,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
63,PRT170043,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
67,PRT170046,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
69,PRT170047,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
72,PRT170049,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
76,PRT170053,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
79,PRT170055,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2
80,PRT170056,NaN,NaN,2017-02-02,3.0,NaN,NaN,2.0,2
81,PRT170057,NaN,NaN,2017-02-02,3.0,NaN,NaN,0.0,2
...,...,...,...,...,...,...,...,...,...
1054,PRT190944,NaN,NaN,2019-03-13,3.0,2.0,0.0,NaN,0
1055,PRT190945,NaN,NaN,2019-03-13,3.0,2.0,0.0,NaN,0
1056,PRT190946,NaN,NaN,2019-03-13,3.0,2.0,2.0,NaN,0
1057,PRT190947,NaN,NaN,2019-03-13,3.0,2.0,2.0,NaN,0
1058,PRT190948,NaN,NaN,2019-03-13,3.0,2.0,0.0,NaN,0
1059,PRT190949,NaN,NaN,2019-03-13,3.0,2.0,2.0,NaN,0
1060,PRT190950,NaN,NaN,2019-03-13,3.0,2.0,2.0,NaN,0
1062,PRT190952,NaN,NaN,2019-04-05,3.0,2.0,2.0,NaN,0
1063,PRT190953,NaN,NaN,2019-04-08,3.0,2.0,0.0,NaN,0
1064,PRT190954,NaN,NaN,2019-04-08,3.0,2.0,2.0,NaN,0
1065,PRT190955,NaN,1969-07-14,2019-04-10,1.0,2.0,2.0,NaN,0
1066,PRT190956,NaN,NaN,2019-04-10,3.0,2.0,0.0,NaN,0
1067,PRT190957,NaN,1950-09-18,2019-04-11,3.0,2.0,0.0,NaN,0
1070,PRT190960,NaN,NaN,2019-04-12,1.0,2.0,2.0,NaN,0
1076,PRT190966,841575322.0,1974-08-03,2019-04-17,1.0,2.0,0.0,NaN,0
1077,PRT190967,841780059.0,1944-11-26,2019-04-18,1.0,2.0,2.0,NaN,0
1079,PRT190969,842945069.0,1969-07-03,2019-04-19,1.0,2.0,2.0,NaN,0
1080,PRT190970,842243292.0,1984-07-01,2019-04-23,2.0,2.0,2.0,NaN,0
1081,PRT190971,NaN,1984-09-08,2019-04-23,1.0,2.0,0.0,NaN,0
1092,PRT190982,NaN,NaN,2019-04-29,3.0,2.0,0.0,NaN,0
1093,PRT190983,841122461.0,1979-02-18,2019-04-29,1.0,2.0,0.0,NaN,0
1094,PRT190984,841842304.0,1964-03-26,2019-04-29,1.0,2.0,0.0,NaN,0
1100,PRT190990,NaN,NaN,2019-05-06,3.0,2.0,0.0,NaN,0
1103,PRT190993,842792814.0,1972-06-09,2019-05-09,1.0,2.0,0.0,NaN,0
1104,PRT190994,75649688.0,1955-01-06,2019-05-09,1.0,2.0,0.0,NaN,0
1105,PRT190995,84203979.0,1960-10-13,2019-05-10,1.0,2.0,0.0,NaN,0
1106,PRT190996,NaN,1979-04-16,2019-05-10,1.0,2.0,0.0,NaN,0
1107,PRT190997,NaN,1977-04-16,2019-05-10,3.0,2.0,0.0,NaN,0
1113,PRT191003,842243510.0,1973-11-22,2019-05-14,1.0,2.0,0.0,NaN,0
1116,PRT191006,75430616.0,1943-01-14,2019-05-15,1.0,2.0,0.0,NaN,0

In [44]:
subject_group = {
    1:"MS",
    2:"Other related disorder",
    3:"Control",
}

In [45]:
complete = {
    0:"Incomplete",
    1:"Unverified",
    2:"Complete",
}

In [46]:
a1['primary_questionnaire_complete'] = a1['primary_questionnaire_complete'].map(complete)

C:\Users\ridhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [47]:
a1['promote_self_reported_outcomes_complete'] = a1['promote_self_reported_outcomes_complete'].map(complete)

C:\Users\ridhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [48]:
a1['update_questionnaire_complete'] = a1['update_questionnaire_complete'].map(complete)

C:\Users\ridhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [49]:
a1['food_frequency_complete'] = a1['food_frequency_complete'].map(complete)

C:\Users\ridhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [50]:
a1['subject_group'] = a1['subject_group'].map(subject_group)

C:\Users\ridhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [51]:
a1

,id_participant_l,id_med_record_number,dob,doe,subject_group,primary_questionnaire_complete,promote_self_reported_outcomes_complete,update_questionnaire_complete,food_frequency_complete
4,PRT170003,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
10,PRT170009,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
12,PRT170010,NaN,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete
16,PRT170013,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
19,PRT170015,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
21,PRT170016,NaN,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete
25,PRT170020,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
27,PRT170021,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
29,PRT170022,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
31,PRT170023,NaN,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete
33,PRT170024,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
36,PRT170027,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
39,PRT170029,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
41,PRT170030,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
43,PRT170031,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
45,PRT170032,NaN,NaN,NaN,NaN,NaN,NaN,Incomplete,Complete
48,PRT170034,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
50,PRT170035,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
52,PRT170036,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
54,PRT170037,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
59,PRT170041,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
61,PRT170042,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
63,PRT170043,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
67,PRT170046,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Incomplete
69,PRT170047,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
72,PRT170049,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
76,PRT170053,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
79,PRT170055,NaN,NaN,NaN,NaN,NaN,NaN,Complete,Complete
80,PRT170056,NaN,NaN,2017-02-02,Control,NaN,NaN,Complete,Complete
81,PRT170057,NaN,NaN,2017-02-02,Control,NaN,NaN,Incomplete,Complete
...,...,...,...,...,...,...,...,...,...
1054,PRT190944,NaN,NaN,2019-03-13,Control,Complete,Incomplete,NaN,Incomplete
1055,PRT190945,NaN,NaN,2019-03-13,Control,Complete,Incomplete,NaN,Incomplete
1056,PRT190946,NaN,NaN,2019-03-13,Control,Complete,Complete,NaN,Incomplete
1057,PRT190947,NaN,NaN,2019-03-13,Control,Complete,Complete,NaN,Incomplete
1058,PRT190948,NaN,NaN,2019-03-13,Control,Complete,Incomplete,NaN,Incomplete
1059,PRT190949,NaN,NaN,2019-03-13,Control,Complete,Complete,NaN,Incomplete
1060,PRT190950,NaN,NaN,2019-03-13,Control,Complete,Complete,NaN,Incomplete
1062,PRT190952,NaN,NaN,2019-04-05,Control,Complete,Complete,NaN,Incomplete
1063,PRT190953,NaN,NaN,2019-04-08,Control,Complete,Incomplete,NaN,Incomplete
1064,PRT190954,NaN,NaN,2019-04-08,Control,Complete,Complete,NaN,Incomplete
1065,PRT190955,NaN,1969-07-14,2019-04-10,MS,Complete,Complete,NaN,Incomplete
1066,PRT190956,NaN,NaN,2019-04-10,Control,Complete,Incomplete,NaN,Incomplete
1067,PRT190957,NaN,1950-09-18,2019-04-11,Control,Complete,Incomplete,NaN,Incomplete
1070,PRT190960,NaN,NaN,2019-04-12,MS,Complete,Complete,NaN,Incomplete
1076,PRT190966,841575322.0,1974-08-03,2019-04-17,MS,Complete,Incomplete,NaN,Incomplete
1077,PRT190967,841780059.0,1944-11-26,2019-04-18,MS,Complete,Complete,NaN,Incomplete
1079,PRT190969,842945069.0,1969-07-03,2019-04-19,MS,Complete,Complete,NaN,Incomplete
1080,PRT190970,842243292.0,1984-07-01,2019-04-23,Other related disorder,Complete,Complete,NaN,Incomplete
1081,PRT190971,NaN,1984-09-08,2019-04-23,MS,Complete,Incomplete,NaN,Incomplete
1092,PRT190982,NaN,NaN,2019-04-29,Control,Complete,Incomplete,NaN,Incomplete
1093,PRT190983,841122461.0,1979-02-18,2019-04-29,MS,Complete,Incomplete,NaN,Incomplete
1094,PRT190984,841842304.0,1964-03-26,2019-04-29,MS,Complete,Incomplete,NaN,Incomplete
1100,PRT190990,NaN,NaN,2019-05-06,Control,Complete,Incomplete,NaN,Incomplete
1103,PRT190993,842792814.0,1972-06-09,2019-05-09,MS,Complete,Incomplete,NaN,Incomplete
1104,PRT190994,75649688.0,1955-01-06,2019-05-09,MS,Complete,Incomplete,NaN,Incomplete
1105,PRT190995,84203979.0,1960-10-13,2019-05-10,MS,Complete,Incomplete,NaN,Incomplete
1106,PRT190996,NaN,1979-04-16,2019-05-10,MS,Complete,Incomplete,NaN,Incomplete
1107,PRT190997,NaN,1977-04-16,2019-05-10,Control,Complete,Incomplete,NaN,Incomplete
1113,PRT191003,842243510.0,1973-11-22,2019-05-14,MS,Complete,Incomplete,NaN,Incomplete
1116,PRT191006,75430616.0,1943-01-14,2019-05-15,MS,Complete,Incomplete,NaN,Incomplete

In [52]:
old = pd.read_csv(input_pre + 'old.csv')

In [53]:
old
main_columns = list(old)
main_complete = [x for x in main_columns if 'complete' in x]

In [54]:
main_complete

['primary_questionnaire_complete', 'promote_self_reported_outcomes_complete']

In [55]:
main_df = old[(old['promote_self_reported_outcomes_complete']==2) | (old['primary_questionnaire_complete']==2)]

In [56]:
a2 = main_df[['record_id','dob_pq','primary_questionnaire_complete','promote_self_reported_outcomes_complete']]

In [57]:
#new = pd.concat([a1, a2])

In [58]:
#new.to_csv("old_temp.csv")

In [59]:
a2

,record_id,dob_pq,primary_questionnaire_complete,promote_self_reported_outcomes_complete
0,1,1993-01-14,2,2
1,2,1976-03-29,2,2
2,3,1959-06-04,2,2
3,4,1951-09-25,2,2
4,5,1968-10-11,2,2
5,6,1980-11-05,2,2
6,7,1957-05-30,2,2
7,8,1966-05-24,2,2
8,9,1959-06-13,2,2
9,10,1972-07-03,2,2
10,11,1950-02-23,2,2
11,12,1982-05-27,2,2
12,14,1968-08-13,2,2
13,15,1980-01-02,2,2
14,16,1961-07-12,2,2
15,18-PRT170053,1978-03-12,2,2
16,19,1958-06-09,2,0
17,20,1971-12-01,2,2
18,21,1942-02-04,2,2
19,22,1967-10-03,2,2
20,23,1971-03-28,2,2
21,24,1963-08-25,2,2
22,25,1962-07-24,2,0
23,26,1941-12-27,2,0
24,27,1952-10-18,2,2
25,28,1961-12-03,2,2
26,29,1976-01-25,2,2
27,30,1986-08-06,2,2
28,31,1949-07-02,2,2
29,32,1957-02-22,2,2
...,...,...,...,...
529,538,1966-02-11,2,2
530,539,1973-03-17,2,2
531,540,1952-10-09,2,0
532,541,1981-06-18,2,2
533,542,1955-01-31,2,2
534,543,1985-06-11,2,2
535,544,1958-10-12,2,2
537,546,1965-01-11,2,2
538,547,1981-02-09,2,2
539,548,1987-06-26,2,2
540,549,1984-08-18,2,2
541,550,1970-08-21,2,2
542,551,1945-10-13,2,0
543,552,1960-10-19,2,2
544,553,1955-12-29,2,0
545,554,1958-03-25,2,2
547,556,1964-07-18,2,2
548,557,1965-02-28,2,2
549,558,1950-05-26,2,0
550,559,1981-10-12,2,0
551,560,1967-03-09,2,0
552,561,1949-06-10,2,0
553,562,1964-05-19,2,0
554,563,1947-04-17,2,2
555,564,1962-03-10,2,2
556,565,1953-11-04,2,2
557,566,1967-01-04,2,0
558,567,1965-08-12,2,2
559,568,1962-03-27,2,0
560,569,1968-07-12,2,2